project_id = "egwagwdvmmyposlsjyje"

[functions.test-gemini]
verify_jwt = false

[functions.generate-categories]
verify_jwt = false

[functions.generate-recipes]
verify_jwt = false

[functions.analyze-dish]
verify_jwt = false
