// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egwagwdvmmyposlsjyje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnd2Fnd2R2bW15cG9zbHNqeWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjI3OTEsImV4cCI6MjA2MjI5ODc5MX0.PdqGIMZKlJal1h208KgpCJ9MQENiI2W5eXFnh3EMKUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);